PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX opm:<http://www.semanticweb.org/ontologies/2011/10/Ontology1322640114011.owl#>
PREFIX vcdm:<http://www.owl-ontologies.com/Ontology1373032300.owl#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT { 
            ?opm_s a opm:OPM_Signal .
            ?opm_s opm:GRP ?kks0 .
            ?opm_s opm:SYS ?kks1 .
            ?opm_s opm:EQP ?kks2 .
            ?opm_s opm:SIG ?kks3 .
            ?opm_s opm:Longtext ?lntext . 
            ?opm_s opm:Komp ?komp .
            ?opm_s opm:BSE ?bse .
            ?opm_s opm:SSE ?sse .
			?opm_s rdfs:label ?label .
}  
WHERE
{
        ?vcdm_s a vcdm:Signal ;
         vcdm:kks0 ?grp ;  
         vcdm:kks1 ?sys ;  
         vcdm:kks2 ?eqp ;  
         vcdm:kks3 ?sig ;  
         vcdm:longText ?lntext ; 
         vcdm:componentNumber ?komp ;  
         vcdm:cpuNumber ?bse ;  
         vcdm:rackID ?sse ; 
         rdfs:label ?label .		 
			
	  	 BIND (URI(CONCAT("http://www.semanticweb.org/ontologies/2011/10/Ontology1322640114011.owl#OPM_Signal_", ?label)) AS ?opm_s)
}

