PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX eplan:<http://www.owl-ontologies.com/Ontology1370788248.owl#>
PREFIX vcdm:<http://www.owl-ontologies.com/Ontology1373032300.owl#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT { ?vcdm_s a vcdm:Signal ;
         vcdm:kks0 ?kks0 ;  
         vcdm:kks1 ?kks1 ;  
         vcdm:kks2 ?kks2 ;  
         vcdm:kks3 ?kks3 ;  
         vcdm:longText ?fntext ; 
         vcdm:componentNumber ?splc1 ;  
         vcdm:cpuNumber ?splc2 ;  
         vcdm:rackID ?splc3 ; 
		 rdfs:label ?label 
}  
WHERE
{
        	?eplan_s a eplan:EPLAN_Signal . 
            ?eplan_s eplan:signalNumber ?snum .
            ?eplan_s eplan:functionText ?fntext .
            ?eplan_s eplan:plcAddress ?plc . 
			?eplan_s rdfs:label ?label .
			
			BIND(xsd:integer(<http://www.w3.org/2005/xpath-functions#substring> (?plc, 1, 3)) AS ?plc1) .
            BIND(xsd:integer(<http://www.w3.org/2005/xpath-functions#substring> (?plc, 5, 2)) AS ?plc2) .
            BIND(xsd:integer(<http://www.w3.org/2005/xpath-functions#substring> (?plc, 8, 2)) AS ?plc3) .
			
			BIND(xsd:string(?plc1) AS ?splc1) .
            BIND(xsd:string(?plc2) AS ?splc2) .
            BIND(xsd:string(?plc3) AS ?splc3) .
			
			BIND(<http://www.w3.org/2005/xpath-functions#substring> (?snum, 1, 1) AS ?kks0) .
            BIND(<http://www.w3.org/2005/xpath-functions#substring> (?snum, 3, 5) AS ?kks1) .
            BIND(<http://www.w3.org/2005/xpath-functions#substring> (?snum, 9, 5) AS ?kks2) .
			BIND(<http://www.w3.org/2005/xpath-functions#substring> (?snum, 15, 4) AS ?kks3) .

            BIND (URI(CONCAT("http://www.owl-ontologies.com/Ontology1373032300.owl#Signal_", ?label)) AS ?vcdm_s)
}

